version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "AppPwd#1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    networks:
      - app-network

  api:
    build: .
    ports:
      - "8084:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__AuthConnection: "Server=ELIO_DOCKER,1433;Database=AuthDb;User Id=AppUser;Password=AppPwd;TrustServerCertificate=true;"
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
