networks:
  inventorynetwork:
services:
  sqlserverinventory:
    container_name: sqlserverinventory
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AppPwd*1234
    ports:
      - "1433:1433"
    networks:
      - inventorynetwork
  inventory.authapi:
    image: ${DOCKER_REGISTRY-}inventoryauthapi
    build:
      context: .
      dockerfile: Inventory.AuthAPI/Dockerfile 
    ports:
      - "5000:80"
    networks:
      - inventorynetwork